apiVersion: v1
kind: Pod
metadata:
  name: pleesah-skute
  namespace: leesah-quiz
spec:
  containers:
    - name: pleesah-skute
      image: # <INSERT IMAGE HERE>
      ports:
        - containerPort: 8080
      resources:
        requests:
          cpu: 50m
          memory: 32Mi
      readinessProbe:
        httpGet:
          port: 8080
          path: /isReady
      env:
        - name: HEV_ANKER
          value: "true"
        - name: SETT_SEIL
          valueFrom:
            secretKeyRef:
              name: seilet-mitt
              key: SETT_SEIL
              optional: true
