apiVersion: v1
kind: Pod
metadata:
  name: pleesah-skute
  namespace: leesah-quiz
spec:
  containers:
    - name: pleesah-skute
      image: ghcr.io/navikt/pleesah-skute:latest
      ports:
        - containerPort: 8080
      resources:
        requests:
          cpu: 50m
          memory: 32Mi
      readinessProbe:
        httpGet:
          port: 8080
          path: /isReady
      livenessProbe:
        httpGet:
          port: 8080
          path: /isAlive
      env:
        - name: HAR_KASTET_LOSS
          value: "true"
        - name: HAR_SATT_KURS
          valueFrom:
            secretKeyRef:
              name: koordinatene-mine
              key: HAR_SATT_KURS
